global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'backend_1'
    static_configs:
      - targets: ['54.171.233.110:8080']

  - job_name: 'backend_2'
    static_configs:
      - targets: ['35.176.245.178:8080']

  - job_name: 'backend_3'
    static_configs:
      - targets: ['35.177.50.235:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']